import { html, TemplateResult } from "lit";

import "./Button";

import { GDSButton } from "@nielsen-media/gds-types";

export default {
  title: "Components/Actions/Button",
  component: "gds-button",
  argTypes: {
    background: {
      options: ["solid", "outlined", "transparent"],
      control: { type: "select" },
      defaultValue: "solid",
    },
    color: {
      options: ["primary", "secondary", "tertiary", "danger"],
      control: { type: "select" },
      defaultValue: "primary",
    },
    rounded: {
      options: ["all", "left", "right", "none"],
      control: { type: "select" },
      defaultValue: "none",
    },
    size: {
      options: ["jumbo", "regular", "compact", "tiny"],
      control: { type: "select" },
      defaultValue: "regular",
    },
    icon: {
      options: [
        "active-check",
        "add-circle",
        "add-custom-list",
        "add-document",
        "add-to-levels",
        "add-user",
        "add",
        "amazon",
        "android",
        "anomaly-status",
        "api",
        "app-switcher",
        "apple-logo",
        "archive",
        "arrow-down",
        "arrow-left",
        "arrow-right",
        "arrow-up",
        "attach",
        "attention",
        "bar-chart-horizontal",
        "bar-chart-vertical",
        "bring-back",
        "bring-backward",
        "bring-forward",
        "bring-front",
        "bubble-chart",
        "calculation-addition",
        "calculation-divide",
        "calculation-equal",
        "calculation-greater-than",
        "calculation-less-than",
        "calculation-multiply",
        "calculation-not-equal",
        "calculation-subtract",
        "calendar",
        "camera",
        "caret-down",
        "caret-left",
        "caret-right",
        "caret-up",
        "checkmark",
        "clear-list",
        "close",
        "collaboration",
        "collapse",
        "column",
        "comment",
        "copy",
        "crop",
        "ctv",
        "currency-dollar",
        "currency-euro",
        "currency-pound",
        "current-event",
        "custom-list",
        "cut",
        "dashboard",
        "data-cube",
        "data-grid",
        "data-pipeline",
        "database",
        "databases",
        "delete",
        "desktop-computer",
        "devices",
        "document",
        "download",
        "duplicate",
        "edit",
        "email",
        "ellipsis",
        "error",
        "expand",
        "export",
        "eye-hide",
        "eye-see",
        "favorites",
        "file-csv",
        "file-excel",
        "file-pdf",
        "file-powerpoint",
        "file-sheets",
        "file-slides",
        "file-zip",
        "filter",
        "flag",
        "flat-list",
        "flat-view",
        "folder",
        "full-screen",
        "full-screen-exit",
        "gracenote",
        "grid",
        "group",
        "hamburger-menu",
        "hiking",
        "households",
        "image",
        "inactive",
        "info",
        "laptop-computer",
        "levels",
        "link",
        "lock",
        "logout",
        "marketing-mix",
        "mass-edit",
        "menu",
        "merge",
        "microsoft",
        "move-drag-horizontal",
        "move-drag-vertical",
        "note",
        "notifications",
        "optimize",
        "organization",
        "page-first",
        "page-last",
        "paste",
        "pause",
        "pending",
        "people",
        "phone-mobile",
        "phone",
        "pin",
        "play",
        "print",
        "privacy-shield",
        "question",
        "radio-feed",
        "redo",
        "refresh",
        "report",
        "reset",
        "reset-alt",
        "retail-store",
        "save",
        "scattered-plot",
        "search",
        "selections",
        "send",
        "settings",
        "share",
        "shopping-purchase",
        "similar-segments",
        "soft-select",
        "sort-alpha",
        "spider-chart",
        "split-screen",
        "status-large",
        "status-small",
        "status",
        "story",
        "subtract",
        "sum",
        "support",
        "syndication",
        "tablet",
        "text",
        "throbber",
        "thumb-down",
        "thumb-up",
        "tree",
        "tv",
        "undo",
        "upload",
        "user-circle",
        "user-square",
        "visualization",
        "warning-alert",
        "with-begins",
        "with-ends",
        "work",
        "zoom-in",
        "zoom-out",
      ],
      control: { type: "select" },
      defaultValue: "none",
    },
    "icon-position": {
      options: ["left", "right"],
      control: { type: "select" },
      defaultValue: "right",
    },
    mode: {
      options: ["light", "dark"],
      control: { type: "select" },
      defaultValue: "light",
    },
    onClick: {
      action: "click",
    },
    disabled: {
      disable: true,
      defaultValue: false,
    },
    width: {
      options: ["auto", "full"],
      control: { type: "select" },
      defaultValue: "auto",
    },
  },
};

interface Story<T> {
  (args: T): TemplateResult;
  args?: Partial<T>;
  argTypes?: Record<string, unknown>;
}

const Template: Story<GDSButton> = ({
  "aria-label": ariaLabel = "gds-button",
  background = "solid",
  color = "primary",
  disabled = false,
  icon = "none",
  "icon-position": iconPosition = "right",
  id = "",
  onClick,
  mode = "light",
  rounded = "all",
  size = "compact",
  width = "auto",
}: GDSButton) =>
  html`<gds-button
    aria-label="${ariaLabel}"
    background=${background}
    color=${color}
    ?disabled=${disabled}
    icon=${icon}
    icon-position=${iconPosition}
    id=${id}
    @click=${onClick}
    mode=${mode}
    rounded=${rounded}
    size=${size}
    width=${width}
  >
    Label
  </gds-button>`;

export const Button = Template.bind({});
Button.args = {
  mode: "light",
  size: "compact",
  color: "primary",
  background: "solid",
  rounded: "all",
  icon: "none",
  "icon-position": "right",
  width: "auto",
  disabled: false,
  id: "",
};
