name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - feature
      - stage
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.4
        with:
          node-version: "14.x"

      - name: Install Dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run prod:gds-web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GEMINI_UI }}
          publish_dir: ./packages/gds-web/storybook-static
          cname: ${{ github.repository_owner }}.github.io
          cname_target: gemini-ui-storybook-${{ github.ref_name }}.mmhuntsberry.com
