name: Deploy Storybook

on:
  push:
    branches:
      - feature
      - stage
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm i --legacy-peer-deps

      - name: Build Storybook
        run: |
          if [[ $GITHUB_REF == "refs/heads/feature" ]]; then
            npm run prod:gds-react
          elif [[ $GITHUB_REF == "refs/heads/stage" ]]; then
            npm run prod:gds-web
          else
            npm run prod:gds-react && npm run prod:gds-web
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GEMINI_UI }}
          publish_dir: ./storybook-static
          cname: ${{ github.ref_name }}-storybook.mmhuntsberry.github.io
          branch: gh-pages
          keep_files: true
          commit_message: "Update Storybook for ${{ github.ref_name }} branch"
          user_name: "GitHub Actions"
          user_email: "github-actions@users.noreply.github.com"
