name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - feature
      - stage
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GEMINI_UI }}
          publish_dir: ./storybook
          cname: ${{ github.repository_owner }}.github.io
          cname_target: gemini-ui-storybook-${{ github.ref }}
