name: Deploy Storybook to GitHub Pages
on:
  push:
    branches:
      - feature/*
      - stage/*
      - prod/*
jobs:
  deploy-gds-web:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build Storybook
        run: npm run prod:gds-web
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy@4.1.1
        with:
          token: ${{ secrets.GEMINI_UI }}
          branch: ${{ github.ref }}
          folder: packages/gds-web/storybook-static
          cleanup: false
          single-commit: true
          commit-message: "Deploy Storybook to ${github.ref}"
          commit-username: "GitHub Actions"
          commit-email: "actions@github.com"
          allow-empty-commit: true
          force-orphan: false
          skip-cleanup: false
          keep-files: false
          verbose: true
          endpoint: https://api.github.com
